# Generated by Django 4.0.3 on 2022-04-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ruta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('Estado', models.BooleanField()),
                ('fechadeentrega', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hoja_de_Ruta',
        ),
        migrations.RemoveField(
            model_name='base',
            name='pedido',
        ),
    ]
