# Generated by Django 4.0.3 on 2022-04-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ruta', '0002_pedido_delete_hoja_de_ruta_remove_base_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='Estado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='movil',
            name='Estado',
            field=models.BooleanField(),
        ),
    ]
