# Generated by Django 4.0.3 on 2022-04-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ruta', '0004_cliente_nro_de_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='movil',
            name='legajo',
            field=models.IntegerField(default=1, unique=True, verbose_name='legajo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='fechadecreacion',
            field=models.DateField(blank=True, null=True, verbose_name='creacion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nro_de_cliente',
            field=models.IntegerField(unique=True, verbose_name='Nro de cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pedido',
            field=models.IntegerField(unique=True, verbose_name='Nro de pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fechadeentrega',
            field=models.DateField(blank=True, null=True, verbose_name='entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.IntegerField(unique=True, verbose_name='Numero'),
        ),
    ]
